# Generated by Django 5.0.6 on 2024-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_number',
        ),
        migrations.AddField(
            model_name='train',
            name='train_name',
            field=models.CharField(default='Sanghmitra Express', max_length=100),
        ),
    ]
